[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  UNDETECTABLE_USER_ID = "55ed6c2b-6bdd-44ea-b0c2-f5f788293072"
  UNDETECTABLE_API_KEY = "eef5d057-ce45-4d80-89b4-2ffa0828e359"
  USE_MOCK_HUMANIZER = "false"
  NEXT_PUBLIC_SUPABASE_URL = "https://uqmmhuqdbmoqaebohbwm.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxbW1odXFkYm1vcWFlYm9oYndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NzgyMzQsImV4cCI6MjA2MzQ1NDIzNH0.FezHZRMpzhs7EdPpYxwaafYzU1sdnm7XzUFT-7x4rC0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
